# -*- coding: utf-8 -*-
"""Data_Analyst_Main_Games_User_Behave.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/intanelaqsha/intanelaqsha/blob/main/Data_Analyst_Main_Games_User_Behave.ipynb
"""

import pandas as pd

# Membaca file CSV
df_premium = pd.read_csv('file_premium.csv')
df_regular = pd.read_csv('file_regular.csv')

# Menyaring kolom yang relevan
relevant_cols = ['user_id', 'clip_id', 'gamesession_Id', 'event_name', 'game_name', 'duration', 'created_at', 'join_at']
df_premium = df_premium[relevant_cols]
df_regular = df_regular[relevant_cols]

# Membedakan pengguna premium dan regular
df_premium.loc[:, 'user_type'] = 'Premium'
df_regular.loc[:, 'user_type'] = 'Regular'

# Menggabungkan kedua data frame
df_combined = pd.concat([df_premium, df_regular])
df_combined.to_csv('COMBINE.csv', index=False)

"""durasi rata-rata klip"""

# Menghitung durasi rata-rata klip untuk setiap jenis pengguna
avg_duration = df_combined.groupby('user_type')['duration'].mean()

print(avg_duration)

# Menghitung jumlah kemunculan setiap event untuk setiap jenis pengguna
top_events = df_combined.groupby(['user_type', 'event_name']).size().reset_index(name='count')
top_events = top_events.sort_values(by='count', ascending=False).groupby('user_type').head(4)

print(top_events)

# Mengubah kolom created_at dan join_at menjadi tipe datetime
df_combined['created_at'] = pd.to_datetime(df_combined['created_at'])

# Menghitung jumlah klip yang dibuat per bulan
clips_per_month = df_combined.groupby([pd.Grouper(key='created_at', freq='M'), 'user_type']).size().unstack()

print(clips_per_month)

import matplotlib.pyplot as plt

# Plot data menggunakan Matplotlib
clips_per_month.plot(kind='bar')
plt.xlabel('Month')
plt.ylabel('Total Clips')
plt.title('Total Clips Created')


# Mengambil 7 karakter awal dari setiap label x
x_labels = [label[:9] for label in clips_per_month.index.strftime('%b %Y')]
plt.xticks(range(len(clips_per_month.index)), x_labels, rotation=45)  # Putar label x-axis agar lebih mudah dibaca

plt.legend(title='User Type')
plt.tight_layout()  # Mengatur layout agar tidak tumpang tindih

# Tampilkan plot
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Visualisasi rata-rata durasi klip
sns.barplot(x=avg_duration.index, y=avg_duration.values, palette='viridis', width=0.6)
plt.title('Average Clip Duration')
plt.xlabel('User Type')
plt.ylabel('Duration (sec)')
plt.show()

# Visualisasi event yang paling sering dilihat
sns.barplot(x='count', y='event_name', hue='user_type', data=top_events, palette='magma', width=0.6)
plt.title('Top Event')
plt.xlabel('Frequency')
plt.ylabel('Event')
plt.show()

# Menghitung jumlah kemunculan setiap event untuk setiap jenis pengguna
top_game = df_combined.groupby(['user_type', 'game_name']).size().reset_index(name='count')
top_game = top_game.sort_values(by='count', ascending=False).groupby('user_type').head(4)

print(top_game)

# Visualisasi event yang paling sering dilihat
sns.barplot(x='count', y='game_name', hue='user_type', data=top_game, palette='cividis', width=0.6)
plt.title('Top game')
plt.xlabel('Frequency')
plt.ylabel('Game Name')
plt.show()